# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    tags:
      - 'v*' # 当推送形如 v1.2.3 的 tag 时触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean publish
    - name: Release with JReleaser
      env:
        # 必须在 GitHub Secrets 中配置这些变量
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        GPG_PUBLIC_KEY: ${{ secrets.OSSRH_GPG_PUBLIC_KEY }}
        GPG_SECRET_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
        JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 这个是 GitHub 自动提供的，无需手动添加
      run: ./gradlew jreleaserFullRelease
